import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-w-screen-xl mx-auto my-10">
      <body className={inter.className}>
        <nav>
          <Navbar />
        </nav>
        {children}

      </body>
    </html>
  );
}
